apiVersion: apps/v1
kind: Deployment 
metadata:
 name: backend
 labels:
     app: backend
     type: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      type: backend
  strategy:
    type: Recreate
  template:
    metadata:
     name: backend
     labels:
        app: backend
        type: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/task1-260513/petclinic-be:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: postgres-config
        env:
          - name: POSTGRES_USER
            value: petclinic
          - name: POSTGRES_PASSWORD
            value: petclinic
          - name: POSTGRES_JDBC_URL
            value: jdbc:postgresql://35.197.78.35:5432/postgres?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true

---
apiVersion: v1
kind: Service
metadata:
    name: service-backend
spec:
    type: NodePort
    ports:
     - targetPort: 8080
       port: 8080
       nodePort: 30016
    selector:
       app: backend
       type: backend
    sessionAffinity: None
    type: NodePort
