apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: petclinic-be
 labels:
     app: petclinic-be
     type: petclinic-be
spec:
  replicas: 1
  selector:
    matchLabels:
      type: petclinic-be
  strategy:
    type: Recreate
  template:
    metadata:
     name: petclinic-be
     labels:
        app: petclinic-be
        type: petclinic-be
    spec:
      containers:
      - name: petclinic-be
        image: gcr.io/task1-260513/petclinic-be:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        env:
          - name: POSTGRES_JDBC_URL
            value: jdbc:postgresql://35.197.78.35:5432/postgres?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
          - name: POSTGRES_USER
            value: petclinic
          - name: POSTGRES_PASSWORD
            value: petclinic

---
apiVersion: v1
kind: Service
metadata:
    name: service-backend
spec:
    type: NodePort
    ports:
     - targetPort: 8080
       port: 8080
       nodePort: 30016
    selector:
       app: petclinic-be
       type: petclinic-be
    sessionAffinity: None
    type: NodePort
