apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: petclinic-be
 labels:
     app: petclinic-be
     tier: backend
     track: stable
spec:
  replicas: 3
  selector:
    matchLabels:
      app: petclinic-be
      tier: backend
      track: stable
  strategy:
    type: Recreate
  template:
    metadata:
     name: petclinic-be
     labels:
      app: petclinic-be
      tier: backend
      track: stable
    spec:
      containers:
      - name: petclinic-be
        image: gcr.io/task1-260513/petclinic-be:latest
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8080
        env:
          - name: POSTGRES_JDBC_URL
            value: jdbc:postgresql://35.197.78.35:5432/petclinic?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
          - name: POSTGRES_USER
            value: petclinic
          - name: POSTGRES_PASSWORD
            value: petclinic

---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-be
spec:
  selector:
    app: petclinic-be
    tier: backend
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: http
