apiVersion: apps/v1 
kind: Deployment 
metadata:
 name: backend
 labels:
     app: backend
spec:
  replicas: 1
  template:
    metadata:
     name: backend
     labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/task1-260513/petclinic-be
        ports:
          - name: postgresql
          - containerPort: 8080
        env:
          - name: POSTGRE_JDBC_USERNAME
            value: petclinic
          - name: SONARQUBE_JDBC_PASSWORD
            value: petclinic
          - name: SONARQUBE_JDBC_URL
            value: jdbc:postgresql://35.197.78.35:5432/postgres?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true

---
apiVersion: v1
kind: Service
metadata:
    name: service-backend
spec:
    type: NodePort
    ports:
     - targetPort: 8080
       port: 8080
       nodePort: 30016
    selector:
       app: backend
    sessionAffinity: None
    type: NodePort
